name: 'Upload and Generate Github documentation page artifacts'

description: 'generate out the html pages for the doc website'

on:
  push:
    branches:
      - 'main'
      - 'master'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        lisp:
          - sbcl-bin

    env:
      LISP: ${{ matrix.lisp }}

    steps:
      - uses: actions/checkout@v2
      - uses: 40ants/setup-lisp@v2
        with:
          asdf-system: geb/documentation
      - name: 'build docs'
        uses: 40ants/run-tests@v2
        with:
          run-tests: |
            (ql:quickload :geb/documentation)
            (uiop:symbol-call 'geb-docs/docs 'build-docs)
            (ql:quickload :geb/test)
            (uiop:symbol-call 'geb-test 'code-coverage)
      - name: Tar files
        run: tar -cvf my_files.tar ./docs
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: my-artifact
          path: my_files.tar

  deploy:
    # Add a dependency to the build job
    needs: build

    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    # Specify runner + deployment step
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
